---
- hosts: localhost

  vars_files:
    - default.config.yml

  tasks:
    - name: Update apt packages
      become: true
      apt:
        name: '{{ install_packages }}' 
        update_cache: yes

